on:
   push:
      branches:
         - master
   pull_request:

name: Unit tests

jobs:
  unitTest:
    name: API Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install latest stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Run cargo test for PREvant domain
        run:
          cargo test --package domain

      - name: Run cargo test for PREvant binary
        run:
          cargo test --package prevant

  doc:
    name: Rust doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install latest stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Run cargo doc
        run:
          cargo doc --package domain
