on:
  push:
    branches:
      - master
  pull_request:

name: Playwright Tests

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      # Make sure to use the same version as playwright dependency in package.json to avoid mismatches
      image: mcr.microsoft.com/playwright:v1.53.1-jammy
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Playwright tests
        working-directory: frontend
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
