apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: prevant
---
apiVersion: v1
kind: Service
metadata:
  name: prevant
  namespace: default
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: prevant
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: prevant
  labels:
    app: prevant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prevant
  template:
    metadata:
      labels:
        app: prevant
    spec:
      serviceAccountName: prevant
      containers:
        - name: prevant
          image: aixigo/prevant
          command:
            - /app/prevant
          args:
            - --runtime-type
            - Kubernetes
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: podinfo
              mountPath: /run/podinfo/
              readOnly: true
      volumes:
        - name: podinfo
          downwardAPI:
             items:
               - path: "labels"
                 fieldRef:
                    fieldPath: metadata.labels
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prevant-ingress-route
spec:
  entryPoints:
    - http
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      priority: -100
      services:
        - name: prevant
          port: 80
