---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: prevant-role
rules:
 - apiGroups:
    - ""
   resources:
    - "*"
   verbs:
    - "*"
 - apiGroups:
    - apps
    - batch
    - storage.k8s.io
    - rbac.authorization.k8s.io
   resources:
    - "*"
   verbs:
    - "*"
 - apiGroups:
    - traefik.containo.us
   resources:
    - middlewares
    - ingressroutes
   verbs:
    - get
    - list
    - create
    - update
    - patch
    - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: prevant-role
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: prevant-role
subjects:
 - kind: ServiceAccount
   name: prevant
   namespace: default

