---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: prevant-role
rules:
 - apiGroups:
    - ""
   resources:
    - endpoints
    - pods
    - pods/log
   verbs:
    - get
    - list
 - apiGroups:
    - ""
   resources:
    - namespaces
    - services
    - secrets
   verbs:
    - get
    - list
    - create
    - update
    - patch
    - delete
 - apiGroups:
    - apps
   resources:
    - deployments
   verbs:
    - get
    - list
    - create
    - update
    - patch
    - delete
 - apiGroups:
    - traefik.containo.us
   resources:
    - middlewares
   verbs:
    - get
    - list
    - create
    - update
    - patch
    - delete
 - apiGroups:
    - traefik.containo.us
   resources:
    - ingressroutes
   verbs:
    - get
    - list
    - create
    - update
    - patch
    - delete
    - apiGroups:
    - ""
   resources:  
    - persistentvolumes
    - persistentvolumeclaims
   verbs:
    - get
    - list
    - create
    - update
    - patch
    - delete
 - apiGroups:
    - ""
   resources:  
    - storageclass
   verbs:
    - get
    - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: prevant-role
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: prevant-role
subjects:
 - kind: ServiceAccount
   name: prevant
   namespace: default

